#!/bin/sh

source prefs

if [ -d .git ]; then
  message=""
  for var in $@; do
    message="$message "$1
    shift
  done
  if [ ${#message} == 0 ]; then
    if [[ -z $default_message ]]; then
      echo "ERROR: You must specify a commit message. If you would like to set a default, please do so by calling:\n\tprefs [-m | --message] MESSAGE"
    else
      message=$default_message
    fi;
  else
    echo "Staging all files...\n"
    git add .
    echo "Committing with message: \"$message\"...\n"
    git commit -m "$message"
    echo "\nPushing to master...\n"
    git push origin $master
    version=$(sw_vers -productVersion)
    if [ version > 10.7 ]; then
      echo "\n😄  🙌  🎉  Successfuly pushed!  🎉  🙌  😄\n"
    else
      echo "\nSuccessfuly pushed!\n"
    fi;
  fi;
else
  echo "This is not a git repository."
fi;
