#!/bin/sh

source prefs

if [ -d .git ]; then
  message=""
  for var in $@; do
    message="$message "$1
    shift
  done
  if [ ${#message} == 0 ]; then
    echo "ERROR: You must specify a commit message. If you would like to set a default, please do so by calling:\n\tprefs [-m | --message] your message"
  else
    echo "Staging all files..."
    git add .
    echo "Committing with message: \"$message\" (that's a clever one)..."
    git commit -m "\"$message\""
    echo "Pushing to master..."
    git push origin $master
  fi;
else
  echo "This is not a git repository."
fi;
